### ISSUE TITLE
Error loading when Neomake is lazy loaded

### ISSUE THREAD

**Issue by tweekmonster** [tweekmonster/nvimdev.nvim#1]
@brcolow brought this up in Gitter:

```
Plug 'neomake/neomake', Cond(has('nvim'), { 'on': 'Neomake' })
```

```
Error detected while processing function <SNR>28_check_nvim[9]..nvimdev#init:
line   56:
E117: Unknown function: neomake#makers#ft#lua#luacheck
E15: Invalid expression: neomake#makers#ft#lua#luacheck()
E117: Unknown function: neomake#makers#ft#lua#luacheck
```

One idea is to create a dummy maker and run `:Neomake! dummy` to trigger loading the plugin.

**Comment by tweekmonster** [comment]
@brcolow Would you confirm that this is actually fixed?

**Comment by brcolow** [comment]
@tweekmonster Seems to still be an issue:

```
Error detected while processing function <SNR>29_check_nvim[9]..nvimdev#init:
line   85:
E117: Unknown function: neomake#makers#ft#lua#luacheck
E15: Invalid expression: neomake#makers#ft#lua#luacheck()
Press ENTER or type command to continue
```

When starting `nvim` without any arguments with the following `init.vim` snippet:

```
Plug 'tweekmonster/nvimdev.nvim', Cond(has('nvim'))
let g:neomake_open_list = 2
Plug 'neomake/neomake', Cond(has('nvim'), { 'on': 'Neomake' })
```

**Comment by tweekmonster** [comment]
@brcolow Hopefully it works now.  I thought vim-plug used `CmdUndefined` but it turns out that's a recent feature.  It creates a proxy `:Neomake` command, so checking for its existence wasn't enough for a positive match.

**Comment by brcolow** [comment]
@tweekmonster It works! Thanks a lot.
