### ISSUE TITLE
[nvimdev] Neomake is not installed

### ISSUE THREAD

**Issue by teto** [tweekmonster/nvimdev.nvim#2]
If I put `Plug 'tweekmonster/nvimdev.nvim'` before `Plug 'XXX/Neomake'`, I have the message:
`[nvimdev] Neomake is not installed`
Moving  `Plug 'tweekmonster/nvimdev.nvim'` right before call plug#end() works fine.

**Comment by tweekmonster** [comment]
Fix incoming.  Thanks!

**Comment by teto** [comment]
No, thanks to you you put up this plugin. I hope to help improve it if need be.

**Comment by tweekmonster** [comment]
🤗
