### ISSUE TITLE
toggle linting on/off

### ISSUE THREAD

**Issue by teto** [tweekmonster/nvimdev.nvim#8]
Linting can be in the way when doing bulk changes (as I have neomake autoopen the location list), thus I would like to enable linting only when finalizing my PRs.

Changing g:nvimdev_auto_lint=0 is not taken into account by neomake.
The issue is related to Neomake's shortcomings but I thought I would create the issue to track progress.

For instance, per maker autoopen would alleviate the problem (so that I can disable autoopen for nvimdev):
https://github.com/neomake/neomake/pull/1064

**Comment by blueyed** [comment]
By now you can use `:NeomakeDisable` (also per buffer or tab, see `:h neomake-disable`).

I think that should be good enough?

**Comment by teto** [comment]
My needs are in fact too changing, I need to write some Fzf utility to enable on the fly linters. 
A constant though is that 90% of the time I prefer having linters not open the location list/qf. So it would be very nice if it could be set per maker.

**Comment by blueyed** [comment]
> So it would be very nice if it could be set per maker.

Makes sense, and should not be too hard after all.
Let's close this here in favor of https://github.com/neomake/neomake/pull/1064 then?

**Comment by teto** [comment]
sure
